### ISSUE TITLE
[Bug] Keywords highlighted and background color changes when using tmux

### ISSUE THREAD

**Issue by angarc** [feline-nvim/feline.nvim#204]
**Neovim version**

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

**Feline version**
I believe I'm using the master branch version? I'm pulling in the plugin like `use 'feline-nvim/feline.nvim'`

**Describe the bug**
All keywords and comments are highlighted but only when using tmux. It looks perfect without tmux, see screenshots. This is code i'm using with Go, but with react and jsx it looks really bad with almost every component tag highlighted making it unusable. Since I use tmux regularly, it's the only thing keeping me from using this theme. Hopefully there's some option i'm not setting yet making this an easy fix.

**To Reproduce**
I just start a tmux session using the `tmux` command and then open up a project in neovim with the `nvim .` command

**Expected behavior**
For it to look the way it does when I'm not using tmux, when i'm using tmux.

**Does this error occur in the minimal init file?**
I didn't use the provided init file, but i did disable every other plugin except for packer and still got the same bug.

I also completely got rid of my tmux config and still got the same bug.
**Screenshots**

### Without tmux
<img width="1680" alt="without_tmux" src="https://user-images.githubusercontent.com/18252779/150659985-bec5d521-268a-4b57-b6b5-184cecbe9085.png">

### With tmux
<img width="1680" alt="Screen Shot 2022-01-22 at 5 28 38 PM" src="https://user-images.githubusercontent.com/18252779/150659967-fd5a1544-7bdf-4896-bbb5-dd43421f9ae7.png">

**Comment by lukas-reineke** [comment]
I think you meant to open this in a different repo? feline is not a colorscheme, it is a stausline.

Regardless, your problem is very likely that the colorscheme is using italic. If you don't have tmux configured to support this, it will show up as background highlight.
You can test this with `echo -e "\e[3m foo \e[23m"` in your terminal while using tmux, this should print `foo` in italic. If it doesn't work, then that's the problem.

You can read more about that here https://rsapkf.xyz/blog/enabling-italics-vim-tmux (or just google)
